version: '3.8'

services:
  database:
    image: postgres:13.6
    container_name: collection_database
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=collection
    logging:
      options:
        max-size: 10m
        max-file: '3'
    ports:
      - '5432:5432'
